### PR TITLE
update messages (JA)

### PR DESCRIPTION
**Pull request by takahashim**
merge commits (EN) 38501281004fcd0145e9babb822285407f5092a8, 6980967d1153044112ade2ff4a4eda6d36cc9649,
d97c5941be6203d0d704db4c13eece0d946d5399, and 2739eb8c31ffcba5653d147e5dcde779081e6797

### CODE REVIEW

**Comment by tofi86** [comment]
Thanks for the translations! I also updated the file in the Transifex system: https://www.transifex.com/idpf/epubcheck/language/ja/

@takahashim, @tomochan001 @skoji there are also some other newly introduced or changed message strings which need to be translated. Have a look at https://www.transifex.com/idpf/epubcheck/language/ja/ to either translate the spanish strings in their webapp or identify the changed/new strings and add them to your PullRequest. If you translate in Transifex I can help an take care of integrating the changes in a PullRequest...

**Comment by takahashim** [comment]
@tofi86 I tried to translate all messages.  Is it OK?

**Comment by tofi86** [comment]
@takahashim looks fine to me, thanks!
I cleaned up the property files from the transifex export:
https://www.dropbox.com/s/qeb5s5sq2tbdytz/epubcheck-localization_transifex-export_JA-598.zip?dl=0

Now you're ready to submit them in this PullRequest.

**Comment by takahashim** [comment]
@tofi86 Thanks!  I'll merge these changes into this PR.

**Comment by takahashim** [comment]
@tofi86 done :smiley_cat:

**Comment by tofi86** [comment]
@takahashim thank YOU! :+1:

@rdeltour Romain, can you squash and merge?

**Comment by tofi86** [comment]
@takahashim Your two commits were squashed and rebased on master to a single commit 4c32d1b. I also added the japanese schematron message file from `src/main/resources/com/thaiopensource/validate/schematron/resources/Messages_ja.properties` which you missed in your second commit.

**Comment by takahashim** [comment]
thank you!

**Pull request closed without merging**
