### PR TITLE
updated spanish message strings for 4.0.0

### PR DESCRIPTION
**Pull request by tofi86**
refs #590 #592 #611

Thanks to @Cuadratin for the Spanish translation!
I committed the files in his name cause there were problems in the original PR #592

@Cuadratin Emiliano, go ahead and test your translation and tell us when you think it's ready to merge.
In case you need to change something, change it on Transifex and tell me here... Thanks :)

### CODE REVIEW

**Comment by Cuadratin** [comment]
Thanks a lot, @tofi86 and excuses for my lack of knowledge of Github workflow.

I'll check the translation today and confirm to you as soon as possible.

**Comment by Cuadratin** [comment]
@tofi86 I've checked the translation and think everything is OK, so if you don't mind could merge it with the main branch.

Thanks again for the help.

**Comment by tofi86** [comment]
@Cuadratin You're welcome! And thanks to YOU for the contribution!

Did you check commandline output works well with accented characters?

**Comment by tofi86** [comment]
:exclamation:  

@Cuadratin committet changes to the translations yesterday (https://www.transifex.com/idpf/epubcheck/viewstrings/#es/ErrorsWarnings/35761361?last_update_gt=2015-09-28)

This PR needs to be updated!

**Comment by tofi86** [comment]
pushed a squashed commit with the latest changes from Transifex.

When CI build is ready, I'll merge these changes to `master`.

Thanks a lot, @Cuadratin! :+1:

**Comment by Cuadratin** [comment]
Thanks to you @tofi86 for your kind help. If you need some other changes, let me know.

**Pull request merged**
