### PR TITLE
Update messages_es.properties

### PR DESCRIPTION
**Pull request by Cuadratin**

### CODE REVIEW

**Comment by rdeltour** [comment]
Thx @Cuadratin ! :+1: 

There are a few additions and changes in regular error messages too (`MessageBundle.properties` files). Not sure how to proceed exactly, e.g. if it's preferable to use Transifex (see #479). @tofi86 any help?

**Comment by tofi86** [comment]
Yeah, I was wondering, too, how to handle the translations... You remember this was one of my concerns in #479? ;-) Well...

Transifex still syncs the english property files with the master branch, so I expect this information to be up-to-date: https://www.transifex.com/idpf/epubcheck/
Okay, I see there has been a problem in syncing the english strings, I've updated the resources manually and re-enabled the auto-sync.
Also added new properties file https://github.com/IDPF/epubcheck/blob/master/src/main/resources/com/thaiopensource/validate/schematron/resources/Messages.properties

Alright @Cuadratin, Transifex is up-to-date and with a Transifex account you're able to either translate the spanish strings in their webapp or identify the changed/new strings and add them to your PullRequest.

**Comment by Cuadratin** [comment]
OK, @tofi86 I'll check Transifex and update the spanish translations there.

Thanks.

**Comment by tofi86** [comment]
@Cuadratin when translating messages, especially in `com/adobe/epubcheck/messages/MessageBundle.properties`, make sure you have the **History** tab opened on the right in Transifex so you can see previous translations for the current message.

bildschirmfoto 2015-09-09 um 23 19 34

This is useful in case @rdeltour only changed a word in the message but not the whole message itself...

**Comment by tofi86** [comment]
@Cuadratin Emiliano, thanks for the translations on Transifex. I cleaned up the Transifex properties files and built a zip file with your changes: https://www.dropbox.com/s/1bncwvpl0ovxqwy/transifex_properties_es.zip?dl=1

Download the zip, unpack it in your epubcheck repo on your PullRequest branch (overwrite this change) and commit the changes as a new commit. I'll take care of the rest, okay?

The cleaning of the Transifex files should also solve the issues with accented characters from ticket #482...

**Comment by Cuadratin** [comment]
Hi @tofi86 

I think I've done the steps you told me. I've tried with Github Desktop for OSX, since I barely know how to use Github at all.

If there's something wrong let me know.

Thanks

**Comment by tofi86** [comment]
@Cuadratin sorry, this didn't work out as you deleted ALL other source files on the new PullRequest #611 :smirk: 
You should have switched to your `patch-5` branch which represents this PullRequest and unpack the zip file without deleting all other files...

I'll go and open a new PulLRequest with your changes. Stay tuned.

**Comment by Cuadratin** [comment]
Sorry very much. Github is totally unknown for me and it's a mess all these branches, commits, pull requests… :(

Tell me if I must upload anything or change whatever.

**Comment by tofi86** [comment]
> Sorry very much. Github is totally unknown for me and it's a mess all these branches, commits, pull requests… :(

No worries, we've all been there ;-)
I committed your translations in the new PR #612 and discussion about the translation should go on there.
If I can help you with GitHub or in understanding Git in some point, just write me a private email.... :-)

**Pull request closed without merging**
