### PR TITLE
Explain another reason mimetype check can fail.

### PR DESCRIPTION
**Pull request by andrewdotn**
The `checkEpubHeader()` method checks the raw EPUB file for the string
`application/epub+zip` starting at byte 38. If the `mimetype` file happens
to be compressed in the zip file, then the check will fail, but the error
message will only say that its contents are invalid.

### CODE REVIEW

**Comment by tofi86** [comment]
related to #530

**Comment by tofi86** [comment]
probably related to #497

**Comment by andrewdotn** [comment]
Helio, any idea when this will be merged in?

**Comment by tofi86** [comment]
Your patch doesn't build so it's likely this will take some time until someone assigns himself to this issue.

**Comment by andrewdotn** [comment]
After updating the warning message in the unit test as well, Travis CI is showing that the code builds and all unit tests pass. Is there something I’m missing?

**Comment by rdeltour** [comment]
LGTM. I'll squash and merge to the master ASAP.

**Comment by andrewdotn** [comment]
Thanks!

**Pull request closed without merging**
