### PR TITLE
[fix #669] compare identifier in opf and ncx

### LINKED ISSUE #669: epubcheck 4 doesn't compare identifier in OPF and NCX anymore
When checking EPUB 2 eBooks, epubcheck 4[.0.1] doesn't compare the identifier value in OPF and NCX anymore.

This is the result in epubcheck 3.0.1:

```
> java -jar epubcheck-3.0.1.jar "C:\Users\Tobias Fischer\Desktop\epub2.epub"
Epubcheck Version 3.0.1

Validating against EPUB version 2.0
WARNING: C:/Users/Tobias Fischer/Desktop/epub2.epub/EPUB/lorem.ncx: meta@dtb:uid content 'urn:uuid:550e8400-e29b-41d4-a716-4466674412314--edit' should conform to unique-identifier in content.opf: 'urn:uuid:550e8400-e29b-41d4-a716-4466674412314'

Check finished with warnings or errors
```

And this is the result of epubcheck 4[.0.1]:

```
> java -Duser.language=en -jar epubcheck.jar "C:\Users\Tobias Fischer\Desktop\epu
b2.epub"
Validating using EPUB version 2.0.1 rules.
No errors or warnings detected.
epubcheck completed
```

I understand that comparing identifiers in EPUB 3 documents isn't required anymore, but I think the WARNING should still be issued when checking EPUB 2 files...

### PR DESCRIPTION
**Pull request by tofi86**
resolves #669

Raised severity level for `NCX_001` from `USAGE` to `ERROR` for both EPUB 2 and EPUB 3

### CODE REVIEW

**Comment by tofi86** [comment]
Boy, those JSON tests are killing me 😭

**Comment by tofi86** [comment]
Thanks Romain! Waiting to merge until we discussed it in the TF.

**Comment by mattgarrish** [comment]
When did it stop being an error? It's been a popularly misunderstood error over the years, and I think most tools that were screwing the IDs up are fixed by now.

But it's one of the somewhat useless error checks, in my opinion. Yes, the identifier of the publication should be consistent wherever it's used, but just as a non-unique package identifier doesn't cause any real issues what supposed problem warrants a mismatch being an error?

What even cares about the identifier in the NCX, in other words? A legacy DAISY player? It feels like ideas of DAISY and EPUB co-existing.

I'm hard-pressed to care about changing the severity, in other words.

**Comment by tofi86** [comment]
> Since this is possibly quite a breaking change (some previously "valid" EPUB would raise an error), maybe we should bring it to tomorrow's call? ping @TzviyaSiegman

missed that, sorry...



> When did it stop being an error? It's been a popularly misunderstood error over the years, and I think most tools that were screwing the IDs up are fixed by now.

This has been a `WARNING` in EpubCheck 3 ever since, but was changes to  `USAGE` with EpubCheck 4.0 by #329

**Comment by mattgarrish** [comment]
> This has been a WARNING in EpubCheck 3 ever since, but was changes to USAGE with EpubCheck 4.0

In that case, it may not be worth changing. The lack of matching affects nothing, and making people fix is not really worth the bother.

**Comment by tofi86** [comment]
@rdeltour via IRC:

```
[19:53] <rdeltour> #798 I'm OK to re-enable the check, it won't affect many people, and the error is pretty straighforward
```

Ok, going to merge it!

**Comment by ptytgat** [comment]
We have difficulties with the check between opf identifier and ncx with epubcheck 4.2.
The opf file contains :  <dc:identifier id="ean">urn:isbn:978207278XXXX</dc:identifier>
The ncx file contains : &lt;meta name="dtb:uid" content="978207278XXXX"/>
This was correct with epubcheck 4.0.x but 4.2 considers that opf identifier and ncx dtb:uid don't match and generates an error : 
ERROR(NCX-001): 
/OPS/toc.ncx(-1,-1): 
L'identifiant NCX ('978207278XXXX') ne correspond pas à l'identifiant 
OPF ('urn:isbn:978207278XXXX').
If we change the value of dtb:uid meta in the ncx file for &lt;meta name="dtb:uid" content="urn:isbn:978207278XXXX"/> it is ok for epubcheck 4.2.
Is it a good practice for the "dtb:uid"  content value ?

**Comment by tofi86** [comment]
This is now the way to go @ptytgat, that's correct.

**Pull request merged**
