### PR TITLE
[WIP] Travis CI: Add JDK9 tests

### PR DESCRIPTION
**Pull request by tofi86**
Java 9 is about to be released in July 2017.
We should make sure that Java 9 is supported by EpubCheck.

### CODE REVIEW

**Comment by tofi86** [comment]
This is a test as I have no idea whether `oraclejdk9` is already supported by Travis CI.
Got mixed search results when trying to figure it out...

**Comment by tofi86** [comment]
Seems to be broken:
https://github.com/travis-ci/travis-ci/issues/5520#issuecomment-306488866

**Comment by tofi86** [comment]
@rdeltour: building the current `master` branch with JDK 9 and Maven 3.5 works well, as long as the tests are skipped:

```
ToFi-MBP in ~/dev/epubcheck
± |master → origin {4} U:1 ?:1 ✗| → mvn -v
Apache Maven 3.5.0 (ff8f5e7444045639af65f6095c62210b5713f426; 2017-04-03T21:39:06+02:00)
Maven home: /usr/local/Cellar/maven/3.5.0/libexec
Java version: 9, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk-9.jdk/Contents/Home
Default locale: de_DE, platform encoding: UTF-8
OS name: "mac os x", version: "10.12.6", arch: "x86_64", family: "mac"

ToFi-MBP in ~/dev/epubcheck
± |master → origin {4} U:1 ?:1 ✗| → java9 -version
java version "9"
Java(TM) SE Runtime Environment (build 9+181)
Java HotSpot(TM) 64-Bit Server VM (build 9+181, mixed mode)

ToFi-MBP in ~/dev/epubcheck
± |master → origin {4} U:1 ?:1 ✗| → mvn package -DskipTests
[INFO] Scanning for projects...
[WARNING] The project org.idpf:epubcheck:jar:4.0.3-SNAPSHOT uses prerequisites which is only intended for maven-plugin projects but not for non maven-plugin projects. For such purposes you should use the maven-enforcer-plugin. See https://maven.apache.org/enforcer/enforcer-rules/requireMavenVersion.html
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] Building EpubCheck :: Validation Tool for EPUB 4.0.3-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-enforcer-plugin:1.0:enforce (enforce-maven) @ epubcheck ---
[INFO] 
[INFO] --- license-maven-plugin:1.14:add-third-party (thirdparty-licenses) @ epubcheck ---
[INFO] Load missing file /Users/tofi/dev/epubcheck/src/main/licenses/third-party.properties
[INFO] Missing file /Users/tofi/dev/epubcheck/src/main/licenses/third-party.properties is up-to-date.
[INFO] Writing third-party file to /Users/tofi/dev/epubcheck/target/generated-sources/license/THIRD-PARTY.txt
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ epubcheck ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 5 resources to /Users/tofi/dev/epubcheck/target
[INFO] Copying 239 resources
[INFO] Copying 1 resource
[INFO] Copying 1 resource
[INFO] 
[INFO] --- xml-maven-plugin:1.0.1:transform (default) @ epubcheck ---
[INFO] Transforming file: /Users/tofi/dev/epubcheck/src/main/resources/com/adobe/epubcheck/schema/30/collection-do-30.sch
[INFO] Transforming file: /Users/tofi/dev/epubcheck/src/main/resources/com/adobe/epubcheck/schema/30/collection-manifest-30.sch
[INFO] Transforming file: /Users/tofi/dev/epubcheck/src/main/resources/com/adobe/epubcheck/schema/30/epub-nav-30.sch
[INFO] Transforming file: /Users/tofi/dev/epubcheck/src/main/resources/com/adobe/epubcheck/schema/30/epub-svg-30.sch
[INFO] Transforming file: /Users/tofi/dev/epubcheck/src/main/resources/com/adobe/epubcheck/schema/30/epub-xhtml-30.sch
[INFO] Transforming file: /Users/tofi/dev/epubcheck/src/main/resources/com/adobe/epubcheck/schema/30/media-overlay-30.sch
[INFO] Transforming file: /Users/tofi/dev/epubcheck/src/main/resources/com/adobe/epubcheck/schema/30/ocf-metadata-30.sch
[INFO] Transforming file: /Users/tofi/dev/epubcheck/src/main/resources/com/adobe/epubcheck/schema/30/package-30.sch
[INFO] Transformed 8 file(s).
[INFO] Transforming file: /Users/tofi/dev/epubcheck/target/generated-resources/intermediate-schema/collection-do-30.sch
[INFO] Transforming file: /Users/tofi/dev/epubcheck/target/generated-resources/intermediate-schema/collection-manifest-30.sch
[INFO] Transforming file: /Users/tofi/dev/epubcheck/target/generated-resources/intermediate-schema/epub-nav-30.sch
[INFO] Transforming file: /Users/tofi/dev/epubcheck/target/generated-resources/intermediate-schema/epub-svg-30.sch
[INFO] Transforming file: /Users/tofi/dev/epubcheck/target/generated-resources/intermediate-schema/epub-xhtml-30.sch
[INFO] Transforming file: /Users/tofi/dev/epubcheck/target/generated-resources/intermediate-schema/media-overlay-30.sch
[INFO] Transforming file: /Users/tofi/dev/epubcheck/target/generated-resources/intermediate-schema/ocf-metadata-30.sch
[INFO] Transforming file: /Users/tofi/dev/epubcheck/target/generated-resources/intermediate-schema/package-30.sch
[INFO] Transformed 8 file(s).
[INFO] 
[INFO] --- maven-compiler-plugin:3.7.0:compile (default-compile) @ epubcheck ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 203 source files to /Users/tofi/dev/epubcheck/target/classes
d[INFO] 
[INFO] >>> maven-bundle-plugin:2.5.4:manifest (bundle-manifest) > process-classes @ epubcheck >>>
[INFO] 
[INFO] --- maven-enforcer-plugin:1.0:enforce (enforce-maven) @ epubcheck ---
[INFO] 
[INFO] --- license-maven-plugin:1.14:add-third-party (thirdparty-licenses) @ epubcheck ---
[INFO] All files are up to date, skip goal execution.
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ epubcheck ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 5 resources to /Users/tofi/dev/epubcheck/target
[INFO] Copying 239 resources
[INFO] Copying 1 resource
[INFO] Copying 1 resource
[INFO] 
[INFO] --- xml-maven-plugin:1.0.1:transform (default) @ epubcheck ---
[INFO] Transforming file: /Users/tofi/dev/epubcheck/target/generated-resources/intermediate-schema/collection-do-30.sch
[INFO] Transforming file: /Users/tofi/dev/epubcheck/target/generated-resources/intermediate-schema/collection-manifest-30.sch
[INFO] Transforming file: /Users/tofi/dev/epubcheck/target/generated-resources/intermediate-schema/epub-nav-30.sch
[INFO] Transforming file: /Users/tofi/dev/epubcheck/target/generated-resources/intermediate-schema/epub-svg-30.sch
[INFO] Transformed 4 file(s).
[INFO] 
[INFO] --- maven-compiler-plugin:3.7.0:compile (default-compile) @ epubcheck ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] <<< maven-bundle-plugin:2.5.4:manifest (bundle-manifest) < process-classes @ epubcheck <<<
[INFO] 
[INFO] 
[INFO] --- maven-bundle-plugin:2.5.4:manifest (bundle-manifest) @ epubcheck ---
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ epubcheck ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 2857 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.7.0:testCompile (default-testCompile) @ epubcheck ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 44 source files to /Users/tofi/dev/epubcheck/target/test-classes
[INFO] 
[INFO] --- maven-surefire-plugin:2.20.1:test (default-test) @ epubcheck ---
[INFO] Tests are skipped.
[INFO] 
[INFO] --- maven-jar-plugin:3.0.2:jar (default-jar) @ epubcheck ---
[INFO] Building jar: /Users/tofi/dev/epubcheck/target/epubcheck.jar
[INFO] 
[INFO] --- maven-dependency-plugin:3.0.2:copy-dependencies (copy) @ epubcheck ---
[INFO] Copying Saxon-HE-9.6.0-10.jar to /Users/tofi/dev/epubcheck/target/lib/Saxon-HE-9.6.0-10.jar
[INFO] Copying commons-compress-1.5.jar to /Users/tofi/dev/epubcheck/target/lib/commons-compress-1.5.jar
[INFO] Copying jing-20120724.0.0.jar to /Users/tofi/dev/epubcheck/target/lib/jing-20120724.0.0.jar
[INFO] Copying sac-1.3.jar to /Users/tofi/dev/epubcheck/target/lib/sac-1.3.jar
[INFO] Copying junit-4.10.jar to /Users/tofi/dev/epubcheck/target/lib/junit-4.10.jar
[INFO] Copying hamcrest-core-1.1.jar to /Users/tofi/dev/epubcheck/target/lib/hamcrest-core-1.1.jar
[INFO] Copying guava-14.0.1.jar to /Users/tofi/dev/epubcheck/target/lib/guava-14.0.1.jar
[INFO] Copying imageio-jpeg-3.1.2.jar to /Users/tofi/dev/epubcheck/target/lib/imageio-jpeg-3.1.2.jar
[INFO] Copying imageio-core-3.1.2.jar to /Users/tofi/dev/epubcheck/target/lib/imageio-core-3.1.2.jar
[INFO] Copying imageio-metadata-3.1.2.jar to /Users/tofi/dev/epubcheck/target/lib/imageio-metadata-3.1.2.jar
[INFO] Copying common-lang-3.1.2.jar to /Users/tofi/dev/epubcheck/target/lib/common-lang-3.1.2.jar
[INFO] Copying common-io-3.1.2.jar to /Users/tofi/dev/epubcheck/target/lib/common-io-3.1.2.jar
[INFO] Copying common-image-3.1.2.jar to /Users/tofi/dev/epubcheck/target/lib/common-image-3.1.2.jar
[INFO] Copying jackson-core-asl-1.9.12.jar to /Users/tofi/dev/epubcheck/target/lib/jackson-core-asl-1.9.12.jar
[INFO] Copying jackson-mapper-asl-1.9.12.jar to /Users/tofi/dev/epubcheck/target/lib/jackson-mapper-asl-1.9.12.jar
[INFO] Copying xmlunit-1.3.jar to /Users/tofi/dev/epubcheck/target/lib/xmlunit-1.3.jar
[INFO] 
[INFO] --- maven-surefire-plugin:2.20.1:test (coverage-test) @ epubcheck ---
[INFO] Tests are skipped.
[INFO] 
[INFO] --- maven-assembly-plugin:3.1.0:single (dist-assembly) @ epubcheck ---
[INFO] Reading assembly descriptor: src/main/assembly/dist.xml
[WARNING] The following patterns were never triggered in this artifact inclusion filter:
o  'com.adobe:epubcheck'

[INFO] Building zip: /Users/tofi/dev/epubcheck/target/epubcheck-4.0.3-SNAPSHOT.zip
[INFO] 
[INFO] --- maven-assembly-plugin:3.1.0:single (src-assembly) @ epubcheck ---
[INFO] Reading assembly descriptor: src/main/assembly/src.xml
[INFO] Building zip: /Users/tofi/dev/epubcheck/target/epubcheck-4.0.3-SNAPSHOT-src.zip
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 30.680 s
[INFO] Finished at: 2017-10-25T22:34:02+02:00
[INFO] Final Memory: 38M/127M
[INFO] ------------------------------------------------------------------------
```

**Comment by tofi86** [comment]
Here's the Java 9 compiled package for testing: 
[epubcheck-4.0.3-SNAPSHOT__compiled-with-JDK9.zip](https://github.com/IDPF/epubcheck/files/1416084/epubcheck-4.0.3-SNAPSHOT__compiled-with-JDK9.zip)

**Comment by tofi86** [comment]
A directory diff does not show any notable differences between the JDK8 and JDK9 compiled versions.

Okay, let's take a look at the failing tests.

**Comment by tofi86** [comment]
Okay, the following tests are failing:

* **`mvn test -Dtest=xhtml_Test#html5_epub3Test`**
  * throws `RSC_005` (ERROR) and `RSC_016` (FATAL) with the same message:
    * Java 8: `The version is required in the XML declaration.`
    * Java 9: `The processing instruction target matching "[xX][mM][lL]" is not allowed.`
  * error thrown for invalid XML PI: `<?xml?>` in `/src/test/resources/com/adobe/epubcheck/test/xhtml/html5_epub3/OPS/xml_version.xhtml`

* **`mvn test -Dtest=package_Test#corrupt_file_Test`** and
**`mvn test -Dtest=package_Test#wrong_type_Test`**
  * throws `PKG_008` (FATAL) with this message:
    * Java 8: `Unable to read file 'error in opening zip file'.`
    * Java 9: `Unable to read file 'zip END header not found'.`
  * error thrown for invalid ZIP file: `/com/adobe/epubcheck/test/package/corrupt_file.epub`
  * error thrown for invalid ZIP file: `/com/adobe/epubcheck/test/package/PlaceHolder.epub`

Everything else works fine.

However, I have no idea how to fix the tests programatically. Do you have an idea, @rdeltour?

Or probably you, @santoch, as you introduced these tests?

**Comment by tofi86** [comment]
@rdeltour any chance you can have a look at this issue this week or beginning of next week?
Would really like to include Java 9 builds in 4.1 release. Ping me you you feel like a discussion between us would help solving this :)

**Comment by rdeltour** [comment]
@tofi86 these 3 diffs in tests don't look too worrying to me, as they're mostly due to change in the error message (probably due to updates in Java's implementation).

I have another failure however, on test `com.adobe.epubcheck.test.script_Test#scriptPropertiesTest`, with a change in expected/actual errors and warning. Do you have this as well?

**Comment by rdeltour** [comment]
> I have another failure however, on test com.adobe.epubcheck.test.script_Test#scriptPropertiesTest

Mmm. Now I can't reproduce it anymore 🤔

**Comment by rdeltour** [comment]
OK, so what I can do is fix the JSON comparing code to loosen the comparison on "message" fields: all text within single quotes can be replaced by some dummy text before being compared. That would fix 2 of the 3 issues.

For the XML declaration issue however (which is probably due to [JEP 255](https://bugs.openjdk.java.net/browse/JDK-8044086)), it would be too permissive to replace all the parsing errors details with dummy text, so I think I would have to hardcode a special case to ensure that the expected error text matches both the Java 8 and Java 9 versions.

**Comment by rdeltour** [comment]
I force-pushed a fix to make the tests pass on Java 9, see 6dfd492b93cd7da7857d27a78cf5cac58f104814.

But now there's another issue due to the coverage tests failing. Somehow the message report file isn't written to disk, maybe there's a problem running the test run listener.

**Comment by tofi86** [comment]
Thank you Romain, that's indeed a good idea. Looks good to me!

Sorry for the hazzle with force-pushing the rebased changes...

**Comment by tofi86** [comment]
Going to squash and merge! 💥

**Pull request merged**
