### PR TITLE
[fix #743] Change --version and -version options to output EpubCheck version

### LINKED ISSUE #743: Add a --version switch
The `epubcheck.jar` should have a `--version` switch to display the version information only.

### PR DESCRIPTION
**Pull request by kamorrissey**
A minimal set of changes to repurpose the "--version" and "-version" command line options to output the EpubCheck program version instead of being undocumented synonyms for the "-v" option. Made sure to update the --help message.

### CODE REVIEW

**Comment by kalaspuffar** [comment]
Looks good to me. Very straightforward. 
I'm not sure if it's required, but there is a class for testing command line features. 
So a unit test could be crafted for this flag.

**Comment by kmorrissey-mersive** [comment]
I looked for command line unit tests and didn't see any. Can anyone point out where they are?

I'll get to this and the cited message this weekend.

**Comment by kmorrissey-mersive** [comment]
I'll get to the requested changes this weekend.

**Comment by kamorrissey** [comment]
I added command line unit tests for version and help.

**Comment by rdeltour** [comment]
Looks good to me, thank you @kamorrissey! 👍

**Comment by tofi86** [comment]
All changes approved, awesome! :)

I suggest we ship this with 4.1 and I'm going to merge it to master in a couple of hours, are you all okay with that?

**Comment by tofi86** [comment]
Merged. Thanks a lot @kamorrissey! 👏 🎉 

Looking forward to seeing more contributions from you! 👍

**Pull request merged**
