### PR TITLE
[fix #647] Update Saxon dependency from 9.5.1-5 to 9.6.0-10

### LINKED ISSUE #647: EPUB Check Java code depends on specific Saxon 9.5 class
So sometimes when using EPUB validation with more recent versions of Saxon (9.6.0.7 in our case) we obtain:

```
        java.lang.ClassNotFoundException: net.sf.saxon.om.Name10Checker
            at java.net.URLClassLoader.findClass(Unknown Source)
            at java.lang.ClassLoader.loadClass(Unknown Source)
            at ro.sync.util.LateDelegationClassLoader.java.lang.Class loadClass(java.lang.String, boolean)(LateDelegationClassLoader.java:0)
            at java.lang.ClassLoader.loadClass(Unknown Source)
            at com.adobe.epubcheck.vocab.PrefixDeclarationParser.parsePrefixMappings(PrefixDeclarationParser.java:105)
            at com.adobe.epubcheck.vocab.VocabUtil.parsePrefixDeclaration(VocabUtil.java:183)
            at com.adobe.epubcheck.opf.OPFHandler30.startElement(OPFHandler30.java:145)
            at com.adobe.epubcheck.xml.XMLParser.startElement(XMLParser.java:542)
            at org.apache.xerces.parsers.AbstractSAXParser.startElement(Unknown Source)
            at org.apache.xerces.impl.XMLNSDocumentScannerImpl.scanStartElement(Unknown Source)
            at org.apache.xerces.impl.XMLNSDocumentScannerImplXerces$NSContentDispatcher.scanRootElementHook(Unknown Source)
            at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(
```

### PR DESCRIPTION
**Pull request by mkraetke**
Update Saxon with respect of the latest Saxon API changes.

### CODE REVIEW

**Comment by tofi86** [comment]
Shall we at least update Saxon 9.6 to the latest maintenance release 9.6.0-10?

@mkraetke did you ever test with a newer version?

**Comment by mkraetke** [comment]
We experienced some issues with versions later than 9.6.0.7, so we consider this version as stable.

**Comment by tofi86** [comment]
@rdeltour gave his okay about updating the saxon dependency:

On 25.08.17 at 20:10 Romain wrote:
> Tobias: about the Saxon dependency issue, I was just worried that a
> maintenance release would break integrations for systems that still use
> the older Saxon version. That said, Saxon 9.5 is pretty old now, so I
> guess we can be blunt and update to 9.6.

* Old version 9.5.1-5 was released in march 2014.
* Proposed version 9.6.0-7 was released in august 2015.
* Latest version of 9.6 branch (9.6.0-10) was released in December 2016.

Despite @mkraetke writing that they experienced issues with newer versions than 9.6.0-7 I'd like to update the saxon dependency at least to the latest version of 9.6 branch.
All unit tests for this are giving good results.

**Comment by tofi86** [comment]
Thanks for your contribution, @mkraetke 👏 🎉

**Comment by mkraetke** [comment]
Glad to help, thank you for your awesome work guys!

**Pull request merged**
