### PR TITLE
Fix 769 allowing aria role attributes in svg

### PR DESCRIPTION
**Pull request by murata0204**
Schema changes required for addressing #769.  Not unit tests (sorry!).

### CODE REVIEW

**Comment by tofi86** [comment]
Thanks for pushing those changes! However, this seems to have quite a few side effects:

```
Failed tests:

  testValidateEPUBTestSvg(com.adobe.epubcheck.api.Epub30CheckTest): The error results do not match expected:<[]> but was:<[MessageId.RSC_005, MessageId.RSC_005, MessageId.RSC_005]>

  testValidateEPUBInvalidNcx(com.adobe.epubcheck.api.Epub30CheckTest): The error results do not match expected:<[MessageId.RSC_012, MessageId.RSC_012]> but was:<[MessageId.RSC_005, MessageId.RSC_005, MessageId.RSC_005, MessageId.RSC_012, MessageId.RSC_012]>

  testValidateEPUBValidNcx(com.adobe.epubcheck.api.Epub30CheckTest): The error results do not match expected:<[]> but was:<[MessageId.RSC_005, MessageId.RSC_005, MessageId.RSC_005]>

  testValidateEPUBMp3(com.adobe.epubcheck.api.Epub30CheckTest): The error results do not match expected:<[]> but was:<[MessageId.RSC_005, MessageId.RSC_005, MessageId.RSC_005]>

  testValidateEPUBInvalidMp3(com.adobe.epubcheck.api.Epub30CheckTest): The error results do not match expected:<[MessageId.OPF_043]> but was:<[MessageId.OPF_043, MessageId.RSC_005, MessageId.RSC_005, MessageId.RSC_005]>

  testValidateEPUBMp3WithFallback(com.adobe.epubcheck.api.Epub30CheckTest): The error results do not match expected:<[]> but was:<[MessageId.RSC_005, MessageId.RSC_005, MessageId.RSC_005]>

  testValidateEPUBPLoremSvg(com.adobe.epubcheck.api.Epub30CheckExpandedTest): The error results do not match expected:<[]> but was:<[MessageId.RSC_005, MessageId.RSC_005, MessageId.RSC_005]>

  testValidateEPUBPLoremSvgHyperlink(com.adobe.epubcheck.api.Epub30CheckExpandedTest): The error results do not match expected:<[]> but was:<[MessageId.RSC_005, MessageId.RSC_005, MessageId.RSC_005]>

  testValidateEPUBPLoremSvgHyperlinkNoTitle(com.adobe.epubcheck.api.Epub30CheckExpandedTest): The error results do not match expected:<[]> but was:<[MessageId.RSC_005, MessageId.RSC_005]>

  testValidateEPUB30_issue134_1(com.adobe.epubcheck.api.Epub30CheckExpandedTest): The error results do not match expected:<[]> but was:<[MessageId.RSC_005, MessageId.RSC_005]>

  testValidateEPUB30_issue134_2(com.adobe.epubcheck.api.Epub30CheckExpandedTest): The error results do not match expected:<[MessageId.OPF_014, MessageId.OPF_014]> but was:<[MessageId.RSC_005, MessageId.OPF_014, MessageId.RSC_005, MessageId.OPF_014]>

  testValidateEPUB30_issue134_3(com.adobe.epubcheck.api.Epub30CheckExpandedTest): The error results do not match expected:<[MessageId.OPF_014]> but was:<[MessageId.RSC_005, MessageId.RSC_005, MessageId.OPF_014]>

  testValidateEPUB30_svgCoverImage(com.adobe.epubcheck.api.Epub30CheckExpandedTest): The error results do not match expected:<[]> but was:<[MessageId.RSC_005, MessageId.RSC_005, MessageId.RSC_005, MessageId.RSC_005, MessageId.RSC_005, MessageId.RSC_005, MessageId.RSC_005, MessageId.RSC_005, MessageId.RSC_005, MessageId.RSC_005, MessageId.RSC_005, MessageId.RSC_005, MessageId.RSC_005, MessageId.RSC_005, MessageId.RSC_005, MessageId.RSC_005, MessageId.RSC_005, MessageId.RSC_005, MessageId.RSC_005]>

  testValidateEPUB30_svgInSpine(com.adobe.epubcheck.api.Epub30CheckExpandedTest): The error results do not match expected:<[]> but was:<[MessageId.RSC_005, MessageId.RSC_005, MessageId.RSC_005, MessageId.RSC_005, MessageId.RSC_005, MessageId.RSC_005, MessageId.RSC_005, MessageId.RSC_005, MessageId.RSC_005, MessageId.RSC_005, MessageId.RSC_005, MessageId.RSC_005, MessageId.RSC_005, MessageId.RSC_005, MessageId.RSC_005, MessageId.RSC_005, MessageId.RSC_005, MessageId.RSC_005, MessageId.RSC_005, MessageId.RSC_005, MessageId.RSC_005, MessageId.RSC_005, MessageId.RSC_005, MessageId.RSC_005, MessageId.RSC_005, MessageId.RSC_005, MessageId.RSC_005, MessageId.RSC_005, MessageId.RSC_005, MessageId.RSC_005, MessageId.RSC_005, MessageId.RSC_005, MessageId.RSC_005, MessageId.RSC_005, MessageId.RSC_005, MessageId.RSC_005, MessageId.RSC_005, MessageId.RSC_005, MessageId.RSC_005, MessageId.RSC_005, MessageId.RSC_005, MessageId.RSC_005, MessageId.RSC_005, MessageId.RSC_005, MessageId.RSC_005, MessageId.RSC_005, MessageId.RSC_005, MessageId.RSC_005, MessageId.RSC_005, MessageId.RSC_005, MessageId.RSC_005, MessageId.RSC_005, MessageId.RSC_005, MessageId.RSC_005, MessageId.RSC_005, MessageId.RSC_005, MessageId.RSC_005, MessageId.RSC_005, MessageId.RSC_005]>

  testValidateEPUB30_svgReferenced(com.adobe.epubcheck.api.Epub30CheckExpandedTest): The error results do not match expected:<[]> but was:<[MessageId.RSC_005, MessageId.RSC_005, MessageId.RSC_005, MessageId.RSC_005, MessageId.RSC_005, MessageId.RSC_005, MessageId.RSC_005, MessageId.RSC_005, MessageId.RSC_005, MessageId.RSC_005, MessageId.RSC_005, MessageId.RSC_005, MessageId.RSC_005, MessageId.RSC_005, MessageId.RSC_005, MessageId.RSC_005, MessageId.RSC_005, MessageId.RSC_005, MessageId.RSC_005]>

  testFXL_WithSVG(com.adobe.epubcheck.api.Epub30CheckExpandedTest): The error results do not match expected:<[]> but was:<[MessageId.RSC_005, MessageId.RSC_005, MessageId.RSC_005, MessageId.RSC_005, MessageId.RSC_005, MessageId.RSC_005, MessageId.RSC_005, MessageId.RSC_005, MessageId.RSC_005, MessageId.RSC_005, MessageId.RSC_005, MessageId.RSC_005, MessageId.RSC_005, MessageId.RSC_005, MessageId.RSC_005, MessageId.RSC_005, MessageId.RSC_005, MessageId.RSC_005, MessageId.RSC_005]>

  testFXL_WithSVG_NoViewbox(com.adobe.epubcheck.api.Epub30CheckExpandedTest): The error results do not match expected:<[MessageId.HTM_048]> but was:<[MessageId.RSC_005, MessageId.RSC_005, MessageId.RSC_005, MessageId.RSC_005, MessageId.RSC_005, MessageId.RSC_005, MessageId.RSC_005, MessageId.RSC_005, MessageId.RSC_005, MessageId.RSC_005, MessageId.RSC_005, MessageId.RSC_005, MessageId.RSC_005, MessageId.RSC_005, MessageId.RSC_005, MessageId.RSC_005, MessageId.RSC_005, MessageId.RSC_005, MessageId.RSC_005, MessageId.HTM_048]>

  testFXL_WithSVGNotInSpine(com.adobe.epubcheck.api.Epub30CheckExpandedTest): The error results do not match expected:<[]> but was:<[MessageId.RSC_005, MessageId.RSC_005, MessageId.RSC_005]>

  viewport_Test(com.adobe.epubcheck.test.opf_Test): Outputted json isn't as expected. (..)

  hyperlinksTest(com.adobe.epubcheck.test.xhtml_Test): Outputted json isn't as expected. (..)

  html5_deprecated_epub3Test(com.adobe.epubcheck.test.xhtml_Test): Outputted json isn't as expected. (..)

  testLoremSVG30(com.adobe.epubcheck.ocf.OCFCheckerTest): expected:<0> but was:<3>

  testLoremHyperlink30(com.adobe.epubcheck.ocf.OCFCheckerTest): expected:<0> but was:<3>

  testValidateSVGRectInvalid(com.adobe.epubcheck.ops.OPSCheckerTest): The error results do not match expected:<[RSC-005, RSC-005, RSC-005, RSC-005]> but was:<[RSC-005, RSC-005, RSC-005, RSC-005, RSC-005, RSC-005, RSC-005]>

  testValidateSVGRectValid(com.adobe.epubcheck.ops.OPSCheckerTest): The error results do not match expected:<[]> but was:<[RSC-005, RSC-005, RSC-005]>

  testValidateXHTMLOPSSVG001(com.adobe.epubcheck.ops.OPSCheckerTest): The error results do not match expected:<[]> but was:<[RSC-005, RSC-005]>

  testValidateXHTMLOPSSVG002(com.adobe.epubcheck.ops.OPSCheckerTest): The error results do not match expected:<[]> but was:<[RSC-005, RSC-005]>

  testValidateXHTML_SVG001(com.adobe.epubcheck.ops.OPSCheckerTest): The error results do not match expected:<[RSC-005, RSC-005]> but was:<[RSC-005, RSC-005, RSC-005, RSC-005]>

  testValidateXHTML_SVGLinks(com.adobe.epubcheck.ops.OPSCheckerTest): The error results do not match expected:<[]> but was:<[RSC-005]>

  testValidateXHTML_SVGLinks_MisssingTitle(com.adobe.epubcheck.ops.OPSCheckerTest): The error results do not match expected:<[]> but was:<[RSC-005]>

  testValidateSVG_Links(com.adobe.epubcheck.ops.OPSCheckerTest): The error results do not match expected:<[]> but was:<[RSC-005, RSC-005, RSC-005, RSC-005]>

  testValidateSVG_ValidStyleWithoutType_issue688(com.adobe.epubcheck.ops.OPSCheckerTest): The error results do not match expected:<[]> but was:<[RSC-005, RSC-005, RSC-005, RSC-005]>

  testValidateSVG_Links_MisssingTitle(com.adobe.epubcheck.ops.OPSCheckerTest): The error results do not match expected:<[]> but was:<[RSC-005, RSC-005, RSC-005]>

  testValidateSVGIssue219(com.adobe.epubcheck.ops.OPSCheckerTest): The error results do not match expected:<[]> but was:<[RSC-005, RSC-005, RSC-005, RSC-005, RSC-005, RSC-005, RSC-005, RSC-005, RSC-005, RSC-005, RSC-005, RSC-005, RSC-005, RSC-005, RSC-005, RSC-005, RSC-005, RSC-005, RSC-005, RSC-005, RSC-005, RSC-005, RSC-005, RSC-005, RSC-005, RSC-005, RSC-005, RSC-005, RSC-005, RSC-005, RSC-005, RSC-005, RSC-005, RSC-005, RSC-005, RSC-005, RSC-005, RSC-005, RSC-005, RSC-005, RSC-005, RSC-005, RSC-005, RSC-005, RSC-005, RSC-005, RSC-005, RSC-005, RSC-005, RSC-005, RSC-005, RSC-005, RSC-005, RSC-005, RSC-005, RSC-005, RSC-005, RSC-005, RSC-005, RSC-005, RSC-005, RSC-005, RSC-005, RSC-005, RSC-005, RSC-005, RSC-005, RSC-005, RSC-005, RSC-005, RSC-005, RSC-005, RSC-005, RSC-005, RSC-005, RSC-005, RSC-005, RSC-005, RSC-005, RSC-005, RSC-005, RSC-005, RSC-005, RSC-005, RSC-005, RSC-005, RSC-005, RSC-005, RSC-005, RSC-005]>
```

I will have to take a closer look at the failing tests and push changes or isolate specific tests.

**Comment by mattgarrish** [comment]
Moving the element declarations to epub-svg11-30.rnc has taken them out of the default SVG namespace. I believe you just need to redeclare in that file:

  default namespace = "http://www.w3.org/2000/svg"

**Comment by murata0204** [comment]
Sorry.  Matt is right.  I introduce a namespace dcl in epub-svg11-30.rnc.

**Comment by tofi86** [comment]
Great! Thanks for the quick fix!

I'm going to review the changes soon and will add a unit test for it based on @rdeltour's initial example in #769

**Comment by tofi86** [comment]
Added a test with the example from #769 and unit tests are fine. Changes approved.

**Pull request merged**
