### PR TITLE
Added translation strings for Italian language

### PR DESCRIPTION
**Pull request by pettarin**
Added translation strings for Italian language.

Built and tested, working properly AFAICT (i.e., with `java -Duser.language=it -jar epubcheck.jar ...`)

### CODE REVIEW

**Comment by tofi86** [comment]
Great, thanks for the contribution, Alberto! :)

Any chance you can squash the commits to a single one for i18n IT and push those to your master?

You should also have a look first at recently merged PR #497 which changes `PKG_005`

**Comment by pettarin** [comment]
Sure, I forgot to rebase. I will look into this next Monday (2015-02-16). I will close this pull request, and open another one w/ the rebased commit.

**Comment by tofi86** [comment]
Leave it open and just rebase your master branch... This will update this PR

**Comment by pettarin** [comment]
That's a nice feature of GitHub I did not know about!

OK, I fetched the remote master update, updated the Italian string for `PKG_005`, squashed, and forced pushed.

It should be OK for you to merge, apologies for forgetting to squash in the first place.

**Comment by telkomsel666** [comment]
#1

**Comment by tofi86** [comment]
Great! But you probably did rebase on the wrong master commit as your `master` tree https://github.com/pettarin/epubcheck/commits/master misses two commits in comparison to https://github.com/IDPF/epubcheck/commits/master, right?

I don't know hwat happens when I'll merge this anyway so I leave it open for now...

**Comment by pettarin** [comment]
I guess the problem was that the fetch from the upstream (which brought in your edits) in the middle of my rebase.

Now I fetched the upstream again, and pushed to my master, so the f092b86 is now "ahead" of the IDPF master, and good for you to merge --- the only diff files are the *_it message files.

Anyhow, if you prefer, just close this pull and I will open another one from a "cleaner state".

**Comment by tofi86** [comment]
Great! This looks perfect now! Thanks for the contribution, Alberto! :+1:

**Pull request merged**
