### PR TITLE
[fix #777] Allow xml:lnag="" by replacing datatype.languagecode by datatype.languagecode | string "".

### LINKED ISSUE #777: Empty attribute "xml:lang" reported as invalid, even though is valid
EpubCheck v4.0.2 (installed via Homebrew on Mac) chokes with `xml:lang` attributes that have no value assigned, such as:

```
<i lang="" xml:lang="">blahblah</i>
```

by saying:

> Error while parsing file 'value of attribute "lang" is invalid; must be an RFC 3066 language identifier'.

But [Language tags in HTML and XML](https://www.w3.org/International/articles/language-tags/) states that: 

> HTML and XML also provide a means to prevent inheritance of language using the empty string, ie. `xml:lang=""`. Essentially, this says: I do not want to associate any language with this information.

### PR DESCRIPTION
**Pull request by murata0204**
This pull request is to address #777.

### CODE REVIEW

**Comment by tofi86** [comment]
Thanks, Makoto san, for providing this fix. Can you probably also add a Java-based unit test for an XHTML file containing this empty lang attribute?

However, if I should better add this, please don't hestitate to say so and I will add a test during review this weekend.

Thanks.

**Comment by murata0204** [comment]
I am afraid that I have not written a Java-based unit test before.  Could you take care of it this time?

**Comment by tofi86** [comment]
> I am afraid that I have not written a Java-based unit test before. Could you take care of it this time?

Sure, no problem! 👍

**Comment by tofi86** [comment]
Test results with 4.0.2 results in error as expected and reported in #777:

```
>java -Duser.language=en -Duser.country=US -jar epubcheck.jar --mode xhtml -v 3.0 "src/test/resources/30/single/xhtml/valid/issue777-empty-lang.xhtml"
ERROR(RSC-005): /src/test/resources/30/single/xhtml/valid/issue777-empty-lang.xhtml/src/test/resources/30/single/xhtml/valid/issue777-empty-lang.xhtml(8,26): Error while parsing file 'value of attribute "lang" is invalid; must be an RFC 3066 language identifier'.
ERROR(RSC-005): /src/test/resources/30/single/xhtml/valid/issue777-empty-lang.xhtml/src/test/resources/30/single/xhtml/valid/issue777-empty-lang.xhtml(8,26): Error while parsing file 'value of attribute "xml:lang" is invalid; must be an RFC 3066 language identifier'.

Check finished with errors

epubcheck completed
```

The version from this PR does not report an error anymore. Travis tests are running, will merge when finished...

**Comment by tofi86** [comment]
Merged. Thanks!

**Pull request merged**
